version: '3.9'

services:
  api:
    build:
      context: .
    container_name: coolevents_api
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
    environment:
      - DEBUG=true
      - DATABASE_URL=postgres://coolevents:coolevents@db:5432/coolevents
      - DATABASE=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine
    container_name: coolevents_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=coolevents
      - POSTGRES_PASSWORD=coolevents
      - POSTGRES_DB=coolevents

volumes:
  postgres_data:
